#!/bin/bash

git_branch() {
    # Check if the current directory is in a Git repository.
    git rev-parse --is-inside-work-tree &>/dev/null || \
        ( [ -z $CONDA_DEFAULT_ENV ] && echo -n '○' ) || return

    BRANCH+="$(git symbolic-ref --quiet --short HEAD 2> /dev/null || \
		git describe --all --exact-match HEAD 2> /dev/null || \
		git rev-parse --short HEAD 2> /dev/null) "
    echo "$BRANCH"
}

env_prompt() {
    if [ ! -z $CONDA_DEFAULT_ENV ]
    then
        echo "$(basename $CONDA_DEFAULT_ENV) "
    fi
}

check_branch() {
    # Check if the current directory is in a Git repository.
    ( git rev-parse --is-inside-work-tree &>/dev/null && echo "± " ) || return
}

text_color() {
    local fg_color=""
    local bg_color=""
    local att=""
    local text="\e["

    for (( var=1;var<=$#;var++ ))
    do
        if [ ${!var} = "-f" ]
        then
            var_next=$((var + 1))
            fg_color=${!var_next}
        elif [ ${!var} = "-b" ]
        then
            var_next=$((var + 1))
            bg_color=${!var_next}
        elif [ ${!var} = "-a" ]
        then
            var_next=$((var + 1))
            att=${!var_next}
        fi
    done

    if [ -n "$att" ]
    then
        text+="$att;"
    fi
    if [ -n "$fg_color" ]
    then
        text+="38;5;$fg_color;"
    fi
    if [ -n "$bg_color" ]
    then
        text+="48;5;$bg_color;"
    fi

    echo -e "${text: : -1}m"
}

user_color() {
    if [ $? = 0 ]
    then
        echo -e "$(text_color -a 1 -f 48)"
    else
        echo -e "$(text_color -a 1 -f 196)"
    fi
}

host_color="\[$(text_color -a 1 -f 4)\]"
git_color="\[$(text_color -a 1 -f 93)\]"
env_color="\[$(text_color -a 1 -f 154)\]"

YELLOW="\[\033[01;33m\]"
WHITE="\[\033[01;37m\]"
RESET="\[\e[0m\]"

PROMPT_DIRTRIM=3

PS1="${debian_chroot:+($debian_chroot)}"

PS1+="\[\$(user_color)\]\u$WHITE@$host_color\h$WHITE [$YELLOW\w$WHITE] "
PS1+="$env_color\$(env_prompt)"
PS1+="$WHITE\$(check_branch)$git_color\$(git_branch)$RESET▸ "

