#!/bin/bash

# some more ls aliases
alias ls=$'ls --group-directories-first --color=auto --time-style="+\e[33m[\e[32m%Y-%m-%d \e[35m%k:%M\e[33m]\e[m"'
alias ll='ls -AlhF --group-directories-first'
alias la='ls -A'
alias l='ls -CF'

# aliases add by user
alias lt='ls -alFht'

alias h='history'

alias dt="date '+%A %B %d %Y %H:%M:%S'"

alias df='df -Th'

alias du='du -h'
alias dul='du --max-depth 1 | sort -rh | head'

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

alias ai='sudo apt-get install'
alias ar='sudo apt-get remove'
alias aar='sudo apt autoremove'
alias au='sudo apt-get update'
alias aug='sudo apt-get upgrade'

alias vi='vim'
alias vim='nvim'

alias rlb='source ~/.bashrc'
alias vib='vim ~/.bashrc'
alias vips='vim ~/.bash/prompt'
alias vial='vim ~/.bash/aliases'
alias vipr='vim ~/.bash/profile'
alias viv='vim ~/.config/nvim/init.vim'

alias cdc='cd /media/halepham/C_DRIVE'
alias cdd='cd /media/halepham/D_DRIVE'
alias cde='cd /media/halepham/EXTENDED'

alias csa='source ~/.bash/conda_init.sh' #'conda activate'
alias csd='conda deactivate'

alias tbw='~/.scripts/tbw.sh'

alias py='python3'
