#!/bin/bash

# make bash expand environment variables to paths on tab completion
shopt -s direxpand

export PATH=$HOME/.cargo/bin:$PATH
export PATH=/usr/local/go/bin:$HOME/go_projects/bin:$PATH
export GOPATH="$HOME/go_projects"
export GOBIN="$GOPATH/bin"
export D_DRIVE=/media/$USER/D_DRIVE
export E_DRIVE=/media/$USER/EXTENDED

### FZF ###
export FZF_DEFAULT_OPTS="                    \
    --bind '?:toggle-preview'                \
    --bind 'ctrl-j:down'                     \
    --bind 'ctrl-k:up'                       \
    --bind 'ctrl-e:preview-down'             \
    --bind 'ctrl-y:preview-up'               \
    --bind 'ctrl-u:preview-page-up'          \
    --bind 'ctrl-d:preview-page-down'        \
    --color=dark                             \
    --color=fg:-1,bg:-1,hl:#5fff87           \
    --color=fg+:-1,bg+:-1,hl+:#ffaf5f        \
    --color=info:#af87ff,prompt:#5fff87      \
    --color=pointer:#ff87d7,marker:#ff87d7   \
    --color=spinner:#ff87d7                  \
    --prompt='∼ ' --pointer='▶' --marker='✗' \
"

# fzf's command
export FZF_DEFAULT_COMMAND="    \
    fd --hidden                 \
       --follow                 \
       --exclude '.git'         \
       --exclude 'node_modules' \
"
# CTRL-T's command
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# ALT-C's command
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND --type d"

export FZF_CTRL_T_OPTS="--preview '([[ -f {} ]] && (bat -n --color=always {} || cat {})) || \
                                   ([[ -d {} ]] && (tree -C {} | less)) ||                  \
                                   echo {} 2> /dev/null | head -200'"
export FZF_CTRL_R_OPTS="--preview 'echo {2..}' --preview-window down:3:wrap"
export FZF_ALT_C_OPTS="--preview '((tree -C {} | less) || file {}) 2> /dev/null | head -200'"
export FZF_TMUX_OPTS='-p90%,60%'
