#!/bin/bash

# some more ls aliases
alias ll='ls -AlhF --group-directories-first'
alias la='ls -A'
alias l='ls -CF'

# aliases add by user
alias lt='ls -alFht'

alias h='history'

alias dt="date '+%A %B %d %Y %H:%M:%S'"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

alias rlb='source ~/.bashrc'
alias vib='vim ~/.bashrc'
alias vips='vim ~/.bash/prompt'
alias vial='vim ~/.bash/aliases'
alias vipr='vim ~/.bash/profile'
alias viv='vim ~/.config/nvim/init.vim'
