#!/bin/bash

# make bash expand environment variables to paths on tab completion
shopt -s direxpand

export GOPATH="$HOME/.go"
export GOBIN="$GOPATH/bin"

export LOCAL_PATH=$HOME/.local
export PATH=$LOCAL_PATH/usr/bin:$LOCAL_PATH/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$GOBIN:$PATH

export LD_LIBRARY_PATH=$LOCAL_PATH/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LOCAL_PATH/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LOCAL_PATH/usr/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LOCAL_PATH/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
export LD_RUN_PATH=$LD_RUN_PATH:$LD_LIBRARY_PATH

export C_INCLUDE_PATH=$LOCAL_PATH/include:$C_INCLUDE_PATH
export C_INCLUDE_PATH=$LOCAL_PATH/usr/include:$C_INCLUDE_PATH
export C_INCLUDE_PATH=$LOCAL_PATH/usr/include/libxml2:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$C_INCLUDE_PATH:$CPLUS_INCLUDE_PATH
export LIBRARY_PATH=$LIBRARY_PATH:$C_INCLUDE_PATH

export PKG_CONFIG_PATH=$LOCAL_PATH/lib/pkgconfig:$PKG_CONFIG_PATH
export PKG_CONFIG_PATH=$LOCAL_PATH/usr/lib/pkgconfig:$PKG_CONFIG_PATH
export PKG_CONFIG_PATH=$LOCAL_PATH/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH

### FZF ###
export FZF_DEFAULT_OPTS="                    \
    --bind '?:toggle-preview'                \
    --bind 'ctrl-j:down'                     \
    --bind 'ctrl-k:up'                       \
    --bind 'ctrl-e:preview-down'             \
    --bind 'ctrl-y:preview-up'               \
    --bind 'ctrl-u:preview-page-up'          \
    --bind 'ctrl-d:preview-page-down'        \
    --color=dark                             \
    --color=fg:-1,bg:-1,hl:#5fff87           \
    --color=fg+:-1,bg+:-1,hl+:#ffaf5f        \
    --color=info:#af87ff,prompt:#5fff87      \
    --color=pointer:#ff87d7,marker:#ff87d7   \
    --color=spinner:#ff87d7                  \
    --prompt='∼ ' --pointer='▶' --marker='✗' \
"

# fzf's command
export FZF_DEFAULT_COMMAND="    \
    fd --hidden                 \
       --follow                 \
       --exclude '.git'         \
       --exclude 'node_modules' \
"
# CTRL-T's command
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# ALT-C's command
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND --type d"

export FZF_CTRL_T_OPTS="--preview '([[ -f {} ]] && (bat -n --color=always {} || cat {})) || \
                                   ([[ -d {} ]] && (tree -C {} | less)) ||                  \
                                   echo {} 2> /dev/null | head -200'"
export FZF_CTRL_R_OPTS="--preview 'echo {2..}' --preview-window down:3:wrap"
export FZF_ALT_C_OPTS="--preview '((tree -C {} | less) || file {}) 2> /dev/null | head -200'"
export FZF_TMUX_OPTS='-p90%,60%'
