# dotfile - Start
if [ -n "$PS1" ]
then
    for file in ~/.bash/{prompt,aliases,profile,completions/*}
    do
	    [ -r "$file" ] && [ -f "$file" ] && source "$file"
    done
    unset file
fi
eval "$(dircolors -b $HOME/.lscolor)"
# dotfile - End
